force-app/main/default/objects/Youtube_Channel__c/Youtube_Channel__c.object-meta.xml
<CustomObject>
    <label>Youtube Channel</label>
    <nameField>
        <label>Youtube Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Youtube Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Youtube_Channel__c/fields/Handle__c.field-meta.xml
<CustomField>
    <fullName>Handle__c</fullName>
    <label>Handle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Youtube_Channel__c/fields/Handle_Encoded__c.field-meta.xml
<CustomField>
    <fullName>Handle_Encoded__c</fullName>
    <label>Handle Encoded</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/YoutubeChannelTriggerHandler.cls
public class YoutubeChannelTriggerHandler {
    public static void beforeInsert(List<Youtube_Channel__c> youtubeChannels) {
        encodeYoutubeHandle(youtubeChannels);
    }
    
    public static void beforeUpdate(
        List<Youtube_Channel__c> youtubeChannels, 
        Map<Id,Youtube_Channel__c> oldMap, 
        Map<Id, Youtube_Channel__c> newMap
    ) {
        encodeYoutubeHandle(youtubeChannels);
    }
    
    public static void encodeYoutubeHandle(List<Youtube_Channel__c> channels) {
        for(Youtube_Channel__c channel: channels) {
            if(channel.Handle__c != null) {
                channel.Handle_Encoded__c = EncodingUtil.urlEncode(channel.Handle__c, 'UTF-8');
            }
        }
    }
}