force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In development</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game_Point__c/Game_Point__c.object-meta.xml
<CustomObject>
    <label>Game Point</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Game Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Game_Point__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Game Points</relationshipLabel>
    <relationshipName>Game_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game_Point__c/fields/Player_Name__c.field-meta.xml
<CustomField>
    <fullName>Player_Name__c</fullName>
    <label>Player Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_Point__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GameController.cls
public without sharing class GameController {
	@AuraEnabled
    public static ShinHelper.ShinGenericResponse getGameBySlug(String slug) {
        List<Game__c> games = [select Id, Name, Status__c, Slug__c from Game__c where Slug__c = :slug limit 1];
        Object res = games.size() > 0 ? games[0] : null;
        return new ShinHelper.ShinGenericResponse(true, 'success', res);
    }
    
    @AuraEnabled
    public static ShinHelper.ShinGenericResponse saveGamePoint(String gameId, String playerName, String points) {
        try {
            Game_Point__c gp = new Game_Point__c();
            gp.Game__c = gameId;
            gp.Player_Name__c = playerName;
            gp.Points__c = Decimal.valueOf(points);
            insert gp;
            ShinHelper.ShinGenericResponse res = new ShinHelper.ShinGenericResponse(true, 'success', (Object) gp);
            return res;
        } catch(Exception e) {
            ShinHelper.notifyError(e);
            ShinHelper.ShinGenericResponse res = new ShinHelper.ShinGenericResponse(false, 'failed', e);
            return res;
        }
    }
}